"""empty message

Revision ID: 26aa344a4bdc
Revises: 64fa40d48423
Create Date: 2020-10-26 18:44:15.779543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aa344a4bdc'
down_revision = '64fa40d48423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
