"""empty message

Revision ID: 2b01d261de9c
Revises: 79ec8072e211
Create Date: 2020-10-26 13:11:55.171604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b01d261de9c'
down_revision = '79ec8072e211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('Venue', sa.Column('web_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'web_address')
    op.drop_column('Venue', 'capacity')
    # ### end Alembic commands ###
