"""empty message

Revision ID: b6bb8331fce4
Revises: 2b01d261de9c
Create Date: 2020-10-26 13:14:36.859060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bb8331fce4'
down_revision = '2b01d261de9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('email', sa.String(length=500), nullable=True))
    op.add_column('Artist', sa.Column('personal_web_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'personal_web_address')
    op.drop_column('Artist', 'email')
    # ### end Alembic commands ###
